.github/workflows/publish.yaml

Update workflow to use node version file

---

.github/actions/setup-node/action.yaml
.github/workflows/publish.yaml
README.md

Update readme with publishing steps

---

.github/workflows/publish.yaml

Add if always()

---

.github/actions/setup-node/action.yaml
.github/workflows/publish.yaml

Consolidate workflow

---

package-lock.json
package.json

Move AWS deps

---

package-lock.json
package.json
src/classes/utils/__tests__/date.spec.ts
src/classes/utils/date.ts

Add custom date formatting

---

package-lock.json
package.json
src/classes/utils/date.ts

Add format arg

---

.secignore
package-lock.json
package.json
src/classes/aws/__tests__/s3-bucket-client.spec.ts
src/classes/aws/__tests__/secrets-manager-client.spec.ts
src/classes/aws/__tests__/ses-client.spec.ts
src/classes/aws/s3-bucket-client.ts
src/classes/aws/ses-client.ts
src/classes/utils/__tests__/date.spec.ts
src/classes/utils/date.ts

Implement SES client

---

.gitignore
package-lock.json
package.json
src/classes/aws/secrets-manager-client.ts
src/classes/aws/ses-client.ts

Update Secrets Manager import statement

---

.gitignore
package-lock.json
package.json
src/classes/aws/__tests__/s3-bucket-client.spec.ts
src/classes/aws/__tests__/secrets-manager-client.spec.ts
src/classes/aws/__tests__/ses-client.spec.ts
src/classes/aws/s3-bucket-client.ts
src/classes/aws/secrets-manager-client.ts
src/classes/aws/ses-client.ts
src/classes/database/session/__tests__/mybatis-session.spec.ts
src/classes/database/session/mybatis-session.ts
src/classes/misc/__tests__/env-vars.spec.ts
src/classes/misc/env-vars.ts
src/classes/utils/__tests__/date.spec.ts
src/classes/utils/date.ts

- Add MyBatis session class
- Fix formatting

Feature / Add MyBatis session class

---

package-lock.json
package.json
src/classes/database/session/__tests__/mybatis-session.spec.ts

Tech / Add MyBatis unit testing

---

package-lock.json
package.json
src/classes/aws/__tests__/dynamo-db-client.spec.ts
src/classes/aws/dynamo-db-client.ts
src/classes/aws/s3-bucket-client.ts
src/classes/aws/secrets-manager-client.ts
src/classes/aws/ses-client.ts

- Add `fullScan` method to Dynamo class

Feat / Add DynamoDB full scan method

---

package-lock.json
package.json
src/classes/utils/__tests__/date.spec.ts
src/classes/utils/date.ts

Update DateTime at to return null if nullish value passed in

---

package-lock.json
package.json
src/classes/utils/date.ts

Create Standard uk date time adapter

---

package-lock.json
package.json
src/classes/utils/date.ts

Feat / Create Standard uk date adapter

---

package-lock.json
package.json
src/classes/aws/__tests__/dynamo-db-client.spec.ts
src/classes/aws/dynamo-db-client.ts

- Allow the passing of additional params to DynamoDB scan

Feat / Allow passing additional params to Dynamo config

---

.github/workflows/ci.yaml
.prettierrc.json
package-lock.json
package.json
src/classes/aws/__tests__/dynamo-db-client.spec.ts
src/classes/aws/__tests__/s3-bucket-client.spec.ts
src/classes/aws/__tests__/secrets-manager-client.spec.ts
src/classes/aws/__tests__/ses-client.spec.ts
src/classes/aws/dynamo-db-client.ts
src/classes/aws/s3-bucket-client.ts
src/classes/aws/secrets-manager-client.ts
src/classes/aws/ses-client.ts
src/classes/database/session/__tests__/mybatis-session.spec.ts
src/classes/database/session/mybatis-session.ts
src/classes/misc/__tests__/env-vars.spec.ts
src/classes/misc/env-vars.ts
src/classes/utils/__tests__/date.spec.ts
src/classes/utils/date.ts
src/response/__tests__/create.spec.ts

tech: Add CI workflow

---

package-lock.json
package.json

Adds a feature flags endpoint for the VTA/M/x clients of CVS.
This endpoint returns a JSON formatted response of the feature flags available from AppConfig.
Related issue: [CB2-10573](https://dvsa.atlassian.net/browse/CB2-10573)

feat(CB2-10573): Implement AWS AppConfig Feature Flagging

---

package-lock.json
package.json
src/functions/sqsFilter.ts
src/functions/sqsModifyFilter.ts

We use a SQS eventname filter in a lot of places. This makes it common and useable across multiple services.
Related issue: [10603](https://dvsa.atlassian.net/browse/CB2-10603)

feat(cb2-10603): add SQS filter

---

package-lock.json
package.json

fix(dependencies): bump `mysql2` to remove critical vulnerability

---

package-lock.json
package.json

Related issue: [CB2-11778](https://dvsa.atlassian.net/browse/CB2-11778)

feat(cb2-11778): update MySQL2

---

package-lock.json
package.json
src/classes/aws/dynamo-db-client.ts
src/classes/aws/s3-bucket-client.ts
src/classes/aws/secrets-manager-client.ts
src/classes/aws/ses-client.ts

feat: add aws xray wrapper to v3 clients

---

.github/actions/publish-package/action.yaml
.github/workflows/publish.yaml

fix: remove un-needed checkout step

---

.github/actions/publish-package/action.yaml
.github/workflows/publish.yaml

feat: publish action name

---

.github/workflows/publish.yaml

feat: service bundler gha

---

package-lock.json
packages/service-bundler/package-lock.json
packages/service-bundler/package.json

fix: remove main field

---

package-lock.json
packages/service-bundler/package-lock.json
packages/service-bundler/package.json
packages/service-bundler/src/index.ts

feat: update build api for future updates

---

.github/dependabot.yaml

feat: add dependabot integration

---

packages/feature-flags/src/__tests__/config.spec.ts
packages/feature-flags/src/config.ts
packages/feature-flags/src/feature-flags.ts

Related issue: [CB2-12591](https://dvsa.atlassian.net/browse/CB2-12591)

fea(cb2-12591): add request timeout to app profile call

---

packages/feature-flags/package.json

the last PR didn't bump the version, this does.

feat(*): update version number in feature flags for publishing

---

packages/feature-flags/package.json

Some files missed duing the package and publishing states

feat(*) update files packaged in package

---

package-lock.json
packages/database/package.json

fix: update clean command

---

package-lock.json
packages/aws-utils/package.json
packages/aws-utils/src/classes/dynamo-db-client.ts

fix: dynamo client init

---

package-lock.json
packages/database/package.json
packages/database/src/index.ts

fix: introduce barrel import to publish session class

---

package-lock.json
packages/database/package.json
packages/database/src/session/__tests__/mybatis-session.spec.ts
packages/database/src/session/mybatis-session.ts

refactor: rename select method to query to better represent usage

---

package-lock.json
packages/database/package.json

fix: install class transformer

---

package-lock.json
packages/service-bundler/package.json
packages/service-bundler/src/index.ts

feat: introduce stat on zipped artefacts

---

package-lock.json
packages/service-bundler/package.json
packages/service-bundler/src/index.ts

fix: stat wording

---

.github/actions/publish-package/action.yaml
.github/workflows/ci.yaml
.github/workflows/publish.yaml
.husky/pre-push
package-lock.json
packages/biome-config/README.md
packages/biome-config/package.json
packages/biome-config/src/config.json

feat: biome config

---

package-lock.json
packages/biome-config/package.json
packages/biome-config/src/config.json

feat: add unused import rule to biome

---

package-lock.json
packages/biome-config/package.json
packages/biome-config/src/config.json

fix: update rule for unused imports

---

package-lock.json
packages/aws-utils/package.json
packages/aws-utils/src/classes/__tests__/secrets-manager-client.spec.ts
packages/aws-utils/src/classes/secrets-manager-client.ts

feat: add yaml option to parse secrets

---

package-lock.json
packages/common/package.json
packages/common/src/classes/testTypes/Constants.ts

Related issue: [CB2-13765](https://dvsa.atlassian.net/browse/CB2-13765)

feat(cb2-13765) added new id into central docs list

---

packages/common/package.json
packages/common/src/classes/testTypes/Constants.ts

13806: Add test type id's 47 & 48 to central docs
13802: Add test type id 67 and remove 199 to central docs
Related issue: [CB2-13806](https://dvsa.atlassian.net/browse/CB2-13806)
AND
Related issue: [CB2-13802](https://dvsa.atlassian.net/browse/CB2-13802)

feat(CB2-13806): Pass and issue Documents Centrally (Additional test type id's 47 & 48)

---

package-lock.json
packages/biome-config/package.json
packages/biome-config/src/config.json

chore: bump biome 0.2.0

---

package-lock.json
packages/openapi-schema-generator/package.json
packages/openapi-schema-generator/src/__tests__/index.spec.ts
packages/openapi-schema-generator/src/index.ts

feat: add openapi class support for generating spec

---

package-lock.json
packages/biome-config/package.json
packages/biome-config/src/config.json

feat: implement noConsole warn rule and add peer dep to biome version

---

.husky/pre-commit
.husky/pre-push
package-lock.json
packages/aws-utils/package.json
packages/aws-utils/src/classes/__tests__/Rekognition-client.spec.ts
packages/aws-utils/src/classes/rekognition-client.ts

feat: adding rekognition client

---

package-lock.json
packages/aws-utils/package.json

- update aws dependencies to 3.682

build: update aws dependencies to 3.682

---

package-lock.json
packages/openapi-schema-generator/package.json
packages/openapi-schema-generator/src/__mocks__/models.ts
packages/openapi-schema-generator/src/__tests__/models.spec.ts
packages/openapi-schema-generator/src/index.ts

fix(openapi-schema-generator): create child schemas when requesting converting interface to object

---

package-lock.json
packages/openapi-schema-generator/package.json
packages/openapi-schema-generator/src/__mocks__/models.ts
packages/openapi-schema-generator/src/__tests__/models.spec.ts
packages/openapi-schema-generator/src/index.ts

fix: create const def mapping

---

.github/workflows/publish.yaml
package-lock.json
packages/business-events/package.json

feat: implement auto publishing

---

package-lock.json
packages/business-events/package.json

fix: add rimraf as dev dep to business events pkg

---

package-lock.json
packages/business-events/package.json

fix: add aws-lambda types as dev dep to business events pkg

---

package-lock.json
packages/aws-utils/package.json

refactor: add peer dependencies to the aws utils to ensure consistent usage

---

package-lock.json
packages/business-events/package.json
packages/business-events/src/business-event-validator.ts
packages/business-events/src/event-factory.ts
packages/business-events/src/event-publisher.ts

refactor: remove redundant class properties in business events

---

CODEOWNERS

chore: add additional code owner

---

package-lock.json
packages/openapi-schema-generator/package.json
packages/openapi-schema-generator/src/__mocks__/models.ts
packages/openapi-schema-generator/src/__tests__/models.spec.ts
packages/openapi-schema-generator/src/index.ts

fix: handle props where type could be a undefined union

---

package-lock.json
packages/aws-utils/package.json
packages/aws-utils/src/classes/cloudwatch-client.ts
packages/aws-utils/src/classes/dynamo-db-client.ts
packages/aws-utils/src/classes/rekognition-client.ts
packages/aws-utils/src/classes/s3-bucket-client.ts
packages/aws-utils/src/classes/secrets-manager-client.ts
packages/aws-utils/src/classes/ses-client.ts

fix: aws utils peer update

---

packages/feature-flags/package.json
packages/feature-flags/src/profiles/__tests__/vtx-profile.spec.ts
packages/feature-flags/src/profiles/vtx.ts

Add in new feature flag for automated CT
Related issue: [15364](https://dvsa.atlassian.net/browse/CB2-15364)

feat(cb2-15364): add automated CT feature flag

---

package-lock.json
packages/aws-utils/package.json

chore: aws utils peer dep range

---

package-lock.json
packages/appdev-common/.npmignore
packages/appdev-common/package.json

chore: compile app dev package before distributing

---

package-lock.json
packages/openapi-schema-generator/package.json
packages/openapi-schema-generator/src/__mocks__/models.ts
packages/openapi-schema-generator/src/__tests__/models.spec.ts
packages/openapi-schema-generator/src/index.ts

feat: openapi schema inheritance

---

package-lock.json
packages/openapi-schema-generator/package.json
packages/openapi-schema-generator/src/index.ts

feat: add core generation logic for named and unnamed schemas

---

package-lock.json
packages/cvs-common/package.json
packages/cvs-common/src/api/routing-decorators.ts

feat: routing decorators to account for extra optional branch in path

---

package-lock.json
packages/cvs-common/package.json
packages/cvs-common/src/api/routing-decorators.ts

fix: routing dec branch env var

---

package-lock.json
packages/cvs-common/package.json
packages/cvs-common/src/api/routing-decorators.ts

fix: post decorator route type

---

package-lock.json
packages/appdev-common/package.json
packages/appdev-common/src/index.ts
packages/appdev-common/src/validation/request-body.ts

feat(cb2-16579): validate express request body decorator method

---

package-lock.json
packages/appdev-common/package.json
packages/appdev-common/src/validation/request-body.ts

feat: add ability to validate against an array of objects via decorator

---

package-lock.json
packages/appdev-common/package.json
packages/appdev-common/src/auth/client-credentials.ts

fix: client credentials content type header

---

package-lock.json
packages/appdev-common/package.json
packages/appdev-common/src/auth/auth-checker.ts

- updated auth code with local check

fix: updated auth code with local check

---

package-lock.json
packages/appdev-common/package.json
packages/appdev-common/src/validation/request-body.ts
packages/aws-utils/src/classes/__tests__/dynamo-db-client.spec.ts

fix: add optional args to validate body decorator

---

package-lock.json
packages/appdev-common/jest.config.ts
packages/appdev-common/package.json
packages/appdev-common/src/auth/auth-checker.ts
packages/appdev-common/src/auth/client-credentials.ts
packages/appdev-common/src/auth/verify-jwt.ts
packages/appdev-common/src/index.ts
packages/appdev-common/src/utils/__tests__/date-time.spec.ts
packages/appdev-common/src/utils/date-time.ts

feat: add date time util class to app dev

---

package-lock.json
packages/appdev-common/package.json
packages/appdev-common/src/utils/__tests__/date-time.spec.ts
packages/appdev-common/src/utils/date-time.ts

feat: add `isBetween` date time helper

---

package-lock.json
packages/appdev-common/package.json
packages/appdev-common/src/validation/request-body.ts

feat: add ajv enhanced formats to decorator

---

package-lock.json
packages/appdev-common/package.json
packages/appdev-common/src/validation/request-body.ts
packages/appdev-common/src/validation/validation-error.ts

feat: validation error class

---

package-lock.json
packages/appdev-common/package.json
packages/appdev-common/src/validation/request-body.ts
packages/appdev-common/src/validation/validation-error.ts

feat: format ajv validation enum errors

---

package-lock.json
packages/appdev-common/README.md
packages/appdev-common/package.json
packages/appdev-common/src/index.ts
packages/appdev-common/src/utils/__tests__/compression.spec.ts
packages/appdev-common/src/utils/compression.ts
packages/cvs-common/package.json
packages/cvs-common/src/api/routing-decorators.ts

feat: compression util in appdev package

---

package-lock.json
packages/appdev-common/package.json
packages/appdev-common/src/utils/date-time.ts

fix: datetimezone default to uk

---

package-lock.json
packages/openapi-schema-generator/package.json
packages/service-bundler/package.json
packages/service-bundler/src/index.ts

feat: service bundler merge external list

---

package-lock.json
packages/service-bundler/package.json
packages/service-bundler/src/index.ts

feat: exclude core options from external bundler

---

package-lock.json
packages/database/package.json
packages/database/src/session/mybatis-session.ts

fix: fallback for query insert oracle

---

package-lock.json
packages/appdev-common/package.json
packages/appdev-common/src/utils/__tests__/date-time.spec.ts
packages/appdev-common/src/utils/date-time.ts

feat: add startOf helper to date time class

---

package-lock.json
packages/feature-flags/package.json

fix: update publishing file list in feature flags

---

package-lock.json
package.json
packages/business-events/package.json
packages/openapi-schema-generator/package.json
packages/service-bundler/package.json
packages/service-bundler/src/index.ts

feat: implement tsup in starter packages for greater tree shaking

---

package-lock.json
packages/service-bundler/package.json
packages/service-bundler/src/index.ts

feat: optimistic bundling to reduce artefact size

---

package-lock.json
packages/service-bundler/package.json
packages/service-bundler/src/index.ts

chore: add koa exclusion into bundler

---

package-lock.json
packages/service-bundler/package.json
packages/service-bundler/src/empty-module.ts
packages/service-bundler/src/index.ts
packages/service-bundler/tsup.config.ts

fix: update package aliasing

---

package-lock.json
packages/service-bundler/package.json
packages/service-bundler/src/index.ts

feat: rework optimised bundler

---

package-lock.json
packages/aws-utils/package.json
packages/aws-utils/src/classes/lambda-client.ts

feat: add aws util for lambda client

---

package-lock.json
packages/service-bundler/package.json
packages/service-bundler/src/empty-module.ts

chore: remove bundler logs

---

package-lock.json
packages/appdev-common/package.json
packages/appdev-common/src/auth/client-credentials.ts

feat: add resource option into client creds

---

package-lock.json
packages/feature-flags/README.md
packages/feature-flags/package.json
packages/feature-flags/src/profiles/vtx.ts

feat: test facility feat flags for rds

---

package-lock.json
packages/aws-utils/package.json
packages/aws-utils/src/classes/cloudwatch-client.ts
packages/aws-utils/src/classes/dynamo-db-client.ts
packages/aws-utils/src/classes/eventbridge-client.ts
packages/aws-utils/src/classes/lambda-client.ts
packages/aws-utils/src/classes/rekognition-client.ts
packages/aws-utils/src/classes/s3-bucket-client.ts
packages/aws-utils/src/classes/secrets-manager-client.ts
packages/aws-utils/src/classes/ses-client.ts

feat: add region check to aws utils

---

package-lock.json
packages/appdev-common/package.json
packages/appdev-common/src/http/decorators.ts
packages/appdev-common/src/http/index.ts

feat: add http wrapper to throw when api call is not ok

---

package-lock.json
packages/appdev-common/package.json
packages/appdev-common/src/http/decorators.ts
packages/appdev-common/src/http/index.ts

chore: add doc blocks to appdev http class

---

package-lock.json
packages/service-bundler/package.json
packages/service-bundler/src/empty-module.ts
packages/service-bundler/src/index.ts

feat(@dvsa/service-bundler): parallel artefact creation

---

package-lock.json
packages/aws-utils/package.json
packages/aws-utils/src/classes/dynamo-db-client.ts

fix: add translate config optional argument to ddb helper

---

package-lock.json
packages/appdev-common/package.json
packages/appdev-common/src/utils/decode-payload-middleware.ts
packages/appdev-common/src/utils/encode-payload-interceptor.ts

feat: add encode interceptor and decode middleware helpers

---

package-lock.json
packages/service-bundler/package.json
packages/service-bundler/src/index.ts

fix: native node module files
